### ISSUE TITLE
server doesn't return beaned grass cells as block cell

### ISSUE THREAD

**Issue by ahmadalli** [SharifAIChallenge/AIC18-Server#17]

**Comment by ali-behjati** [comment]
It is not server side, which client do you use?

On Feb 25, 2018 5:20 PM, "ahmadali shafiee" <notifications@github.com>
wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SharifAIChallenge/AIC18-Server/issues/17>, or mute the
thread

**Comment by ahmadalli** [comment]
I'm using the java client.

**Comment by ahmadalli** [comment]
yeah, I red the init codes of client and it's client's problem. probably fixed by https://github.com/SharifAIChallenge/AIC18-Client-Java/pull/11
